### ISSUE TITLE
Vercel Deploy button image blocked due to CSP

### ISSUE THREAD

**Issue by timothyis** [planetscale/docs#116]
In the "Deploy to Vercel" documentation (https://docs.planetscale.com/tutorials/deploy-to-vercel#deploy-to-vercel), under the "Deploy to Vercel" subheading, the image for the Vercel Deploy button does not load. 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/1695613/159995065-c5a8530b-40de-4235-a6fc-846ccdc37bee.png">

This looks to be because of a CSP issue? 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1695613/159995161-0c776081-ab53-4cbc-8447-c85e31c0efab.png">

**Comment by tbarn** [comment]
Fixed last week!
