### ISSUE TITLE
Error when I try db push following the documentation

### ISSUE THREAD

**Issue by yosle** [planetscale/docs#174]
II'm following all the steps in the guide to make changes in the schema and update those changes in planetscale database. connected to planetscale locally but when I run  prisma db run I get this:

`npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "platforms" at "127.0.0.1:3309"

⚠️  There might be data loss when applying the changes:

  • You are about to drop the column `gh_username` on the `User` table, which still 
contains 1 non-null values.
  • You are about to drop the column `image` on the `User` table, which still contains 1 non-null values.
  • You are about to drop the column `name` on the `User` table, which still contains 1 non-null values.

√ Do you want to ignore the warning(s)? ... yes
Error: P3022

Direct execution of DDL (Data Definition Language) SQL statements is disabled on this database. Please read more here how to handle this: https://pris.ly/d/migrate-no-direct-ddl `

So this link refers to the old docs. I really need to change that database schema...kinda stuck here. Really appreciate some help.

**Comment by tbarn** [comment]
Hey @yosle, are you connecting to a development branch when you do this? The error message makes it sound like you might be on a production branch which does not allow DDL.

**Comment by Manubi** [comment]
I have the same problem. I followed the docs and get the same error. After following this article,
https://shadcn.com/next-prisma-planetscale-vercel I run into the problem that I can't open two dev branches with the hobby plan. 
Any other ideas?

**Comment by tbarn** [comment]
@Manubi It looks like that blog post is also using the older recommended way. 

In the new way, you never create a shadow branch, just one where you are developing in alongside your production branch. You can check out the document I link in my last comment for more information. The TLDR is:

1. Make `dev` branch
2. Change `DATABASE_URL` to the connection string for the `dev` branch.
3. Make your Prisma changes locally then `npx prisma db push`
4. Your changes are pushed to the `dev` branch and ready to open a deploy request to your production branch whenever you are ready. 

You can also still use `pscale connect` if you would like, just make sure to have the right `DATABASE_URL` in your env vars.

**Comment by tbarn** [comment]
@yosle I reached out to the Prisma team and we got the URL from the error updated so that it links to somewhere that explains more about development and production branches, including the error message. Since that is now improved, I'm going to close this issue for now. Feel free to follow up in a comment with any more questions about it.
