### ISSUE TITLE
Text overlaps on the main page

### ISSUE THREAD

**Issue by Fyrrj** [planetscale/docs#195]
**Section "The power of open source"**
MacBook Pro (13-inch, M1, 2020) - 1300px

<img width="1438" alt="Zrzut ekranu 2022-08-23 o 09 46 56" src="https://user-images.githubusercontent.com/36820269/186103122-7f053672-4eed-4663-89c9-514bdd14544e.png">

**Comment by llibdude** [comment]
@Fyrrj Thanks for reporting this. I'm having some trouble reproducing, could you provide the browser and version as well? Thanks

**Comment by Fyrrj** [comment]
@llibdude Google Chrome version -> 104.0.5112.101 (arm64)

**Comment by Fyrrj** [comment]
Issue resolved, thanks!
