### ISSUE TITLE
Invisible "connect" button on app/overview

### ISSUE THREAD

**Issue by Fyrrj** [planetscale/docs#196]
I'm currently working on: MacBook Pro (13-inch, M1, 2020) - MacOS Monterey 12.5. Google Chrome version -> 104.0.5112.101 (arm64) On full width there is no "connect" button. On 767px breakpoint there is menu that includes connect button properly. 

Some ss below:
<img width="1415" alt="Zrzut ekranu 2022-08-24 o 11 23 00" src="https://user-images.githubusercontent.com/36820269/186385228-e70920e5-a270-4ff0-af9c-4cd150a42135.png">
<img width="647" alt="Zrzut ekranu 2022-08-24 o 11 23 15" src="https://user-images.githubusercontent.com/36820269/186385241-166a81a0-4481-4f63-bd10-ee5ad0fa894d.png">

**Comment by Fyrrj** [comment]
Seems like container with buttons gets prop "hidden"
<img width="1428" alt="Zrzut ekranu 2022-08-24 o 21 09 36" src="https://user-images.githubusercontent.com/36820269/186503168-c37afced-f167-41d4-a785-428b99cd3883.png">

**Comment by jasonlong** [comment]
Yeah this is actually the correct CSS classes though. We use Tailwind and `hidden` is the default styling at the smallest breakpoints and then at the medium (768px) breakpoint `md:flex` kicks in and make it visible. Your inspector looks the same as mine.

Could you try selecting that next container (the one you've marked with `hidden`) to see what the browser highlights?

**Comment by Fyrrj** [comment]
Sadly nothing is selected on the site 
<img width="1429" alt="Zrzut ekranu 2022-08-24 o 21 45 19" src="https://user-images.githubusercontent.com/36820269/186509339-d11f3c3b-c118-4073-bcf4-bb9ee828b85e.png">

**Comment by jasonlong** [comment]
Thanks for checking. So this is interesting:

![CleanShot 2022-08-24 at 16 27 18@2x](https://user-images.githubusercontent.com/6104/186516889-91796957-e409-4d1e-8174-61e970b39ea9.png)

It looks like something else is injecting a `.hidden` class with `display: none !important` which isn't from our app. Do you have any other user styles defined w/ Stylish or similar extension?

**Comment by Fyrrj** [comment]
Issue resolved, thanks for help!
