### ISSUE TITLE
[UPDATED DOC] Connect a Next.js application to PlanetScale

### ISSUE THREAD

**Issue by jsjoeio** [planetscale/docs#197]
## Which doc needs updating?
https://planetscale.com/docs/tutorials/connect-nextjs-app

## Why is this needed?
Tutorial uses `DATABASE_URL` but actual code uses `PLANETSCALE_PRISMA_DATABASE_URL`

Also running `npx prisma db push` results in an error:

```shell
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "my_database" at "ir3t6fhn0wnu.us-west-2.psdb.cloud:3306"

Error: P1012: error: Error validating: This line is not a valid definition within a datasource.
  -->  schema.prisma:4
   | 
 3 |                 provider = "mysql"
 4 |                 url = "mysql://redacted"             }
   | ```

## Urgency
No

## Additional resources
N/A

## Point of contact
N/A

**Comment by jsjoeio** [comment]
Why was this closed?

**Comment by bmorrisondev** [comment]
@jsjoeio Thanks for reporting this. We updated the doc you reported as well as the sample repo referenced. The changes were just published, so this issue should be resolved. Let me know if you still encounter issues, thanks!

**Comment by jsjoeio** [comment]
Ah got it! Just found the commit: https://github.com/planetscale/nextjs-starter/commit/d36c458b9b40014d35e086e00172f8664a745d39

Thank you!
