### ISSUE TITLE
"Help us improve this page" link is broken

### ISSUE THREAD

**Issue by adrianmg** [planetscale/docs#20]
👋 

https://github.com/planetscale/docs/blob/81b871099a0592ec6d81edc05bebac495c26c0e3/components/PageInfo.js#L58

Slug when looking at tutorials is a 404: `https://github.com/planetscale/docs/blob/main/content/docs/tutorials/connect-any-application.mdx` instead of `https://github.com/planetscale/docs/blob/main/content/docs/tutorial/connect-any-application.mdx` for this lil guy:

![image](https://user-images.githubusercontent.com/589285/131757279-6a79f533-20ed-476f-becf-5d2c2eff9d40.png)

It seems to be taking `tutorials` instead of `tutorial` for some reason 🤷

**Comment by mscoutermarsh** [comment]
This has been fixed! Thanks @adrianmg <3
