### ISSUE TITLE
Error during 'Push Prisma schema to PlanetScale' Section: "server does not allow insecure connections, client must use SSL/TLS"

### ISSUE THREAD

**Issue by NLanese** [planetscale/docs#227]
### What type of content do you want to see?

I have followed the instructions almost exactly to this point (using my own branch name and db name, of course) but whenever I run `npx prisma db push` I get the error shown above, 
```
server does not allow insecure connections, client must use SSL/TLS
```

I have googled that error, but seldom do the solutions seem to be for PlanetScale / Prisma setups

### Is this specific to a language/framework?

Prisma

**Comment by bmorrisondev** [comment]
Hey there @NLanese! Sorry you're having trouble. If you are using a connection string to access the database directly (not through the pscale CLI as described in our docs) you'll need the `sslaccept=strict` query string appended to the connection string. Here is an example with placeholders that should work:

```
DATABASE_URL='mysql://<DB_USERNAME>:<DB_PASSWORD>@<DB_HOST>/<DB_NAME>?sslaccept=strict'
```

Alternately, you can generate a connection string from within the PlanetScale dashboard by clicking the Connect button from the Overview tab and selecting Prisma from the Connect With dropdown. 

![CleanShot 2023-01-09 at 09 24 23](https://user-images.githubusercontent.com/4684030/211330899-f58b8fa6-4143-47aa-851b-7b148c20691e.png)

![CleanShot 2023-01-09 at 09 24 07](https://user-images.githubusercontent.com/4684030/211330947-60e477e8-23ef-46cd-9314-cd496f75fc74.png)

Let me know if this helps.
