### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by lutfuahmet** [planetscale/docs#7]
Documentation not working due to 404 error.

url : https://docs.planetscale.com/tutorial/connect-any-application

screen : 

![image](https://user-images.githubusercontent.com/10168354/122209718-83277f80-cead-11eb-93ad-ab6d480f05d9.png)

**Comment by raunaqgupta** [comment]
Hi @lutfuahmet, thank you for opening the issue. We have pushed some fixes to address this particular issue and would love if you can provide feedback if things have improved for you or not.

**Comment by lutfuahmet** [comment]
it fixed. but there is an other css bug(horizontal scroll at my screen 1280 x 720).

**Comment by raunaqgupta** [comment]
> it fixed. but there is an other css bug(horizontal scroll at my screen 1280 x 720).

Thanks! We will check the horizontal scroll issue separately. Closing this issue for now.
