### ISSUE TITLE
More details about how to deploy to Vercel in production

### ISSUE THREAD

**Issue by futantan** [planetscale/docs#99]
Hi there, the docs are really helpful! 
But I might found something missing when reading https://docs.planetscale.com/tutorials/prisma-quickstart
After finish this page, we got a working NextJS project, and then I'd like to deploy it to Vercel.
The link [Deploy to Vercel guide](https://docs.planetscale.com/tutorials/deploy-to-vercel#deploy-to-vercel) doesn't help since it's a totally different project and the env variables are totally different.

My question is how can I deploy a nextjs project described in https://docs.planetscale.com/tutorials/prisma-quickstart
I'm not sure if the only action I need to do is setting `DATABASE_URL` env variable

**Comment by tbarn** [comment]
Hi @futantan! This is great feedback. We definitely want to work on those "Deploy to ___" guides. 

And to answer your question, yes, this is correct. You only need to add the `DATABASE_URL` which you get for Prisma when you create a Password for your branch.

**Comment by futantan** [comment]
Thank you @tbarn !
